### ISSUE TITLE
Cron not working for CIDRAM in WordPress

### ISSUE THREAD

**Issue by 100percentlunarboy** [Maikuolan/Cronable#3]
Hi

I have spent some time trying to get CIDRAM to update via a cron job and I am still unsuccessful and I was hoping you could give me some assistance.

Here is how I have tried to get it to work.

I have downloaded the file  Cronable.php and put it in the same directory as loader.php

I have used and modified the file examples.php to fit my directory structures adding the user created using the front end with permissions cronable.

To execute I am using the WordPress plugin WP Crontrol to set up a PHP cron event. The plugin is super simple and allows you to take the modified examples.php code and insert it in and set the execution frequency.

I have tried manipulating the examples.php file many times but nothing has worked.

The current errors I am getting is:

I am getting errors like ... 

Warning ... No such file or directory in... eval()'d code on line 12
 
Fatal error: require(): Failed opening required ....   eval()'d code on line 12

I am not sure if I should be posting the full errors here but would send them to you privately if needed.

The line 12 constantly referred to is:

require __DIR__ . '/src/Cronable.php';

I have tried changing the path shown in line 12 and I always get errors. I have tried creating the dir src in the directory structure where WP Crontrol lives and put cronable.php in that directory and all errors go away but CIDRAM is not updated...

Any ideas?

Would be nice if the WordPress install just created the cron job like other WordPress plugins do. I have never had to manually create one before. I use WP Crontrol to easily change the frequency or disable jobs as needed.

Thanks!

**Comment by Maikuolan** [comment]
Hi,

Sorry about the delay in replying. Got busy with other things earlier and had kind of forgotten about this issue.

Seeing an error about eval()'d code is definitely very weird, because Cronable doesn't actually use eval() at all anywhere in its codebase or in any of the examples.

Do you still have my email address handy? I might need to take a closer look at your exact implementation to figure out what's going on there, I think.

Would be tempted to call it a weird WordPress quirk, but I'm actually running Cronable myself for at least two different WordPress installations and haven't had any similar problems, so.. not entirely sure how well that would hold up.

**Comment by Maikuolan** [comment]
I honestly don't actually remember anymore whether we ended up resolving this or not in the end, or much about what happened here, but there hasn't been any activity at this issue at all in almost two years now, since my previous reply, so I'm going to go ahead and mark this as resolved and close it.
