### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by harryqt** [Maikuolan/Cronable#5]
The Cronable was working fine for me. But it has stopped working, don't know since when.

When I execute Cronable, I get this:

`Cronable v1.2.0 Time: Thu, 06 Sep 2018 04:09:23 +0000 === Everything already up-to-date at [CIDRAM@example.com/loader.php]. :-) === Time: Thu, 06 Sep 2018 04:09:23 +0000`

But, in the CIDRAM front-end **I can see updates.**

![CIDRAM Update-Available](https://s.put.re/A3yrNiq.png)

My update script is this:

```php
<?php

/** Requiring the Cronable class file. */
require __DIR__ . '/src/Cronable.php';

/** Importing the Cronable class from its namespace. */
use \Maikuolan\Cronable\Cronable;

/** Instantiate a new object from the Cronable class. */
$Cronable = new Cronable;

$Cronable->createTask('CIDRAM', 'username', 'password', 'http://example.com/loader.php');

/** After you've created your tasks, you'll want to execute them all. */
$Cronable->execute();

echo $Cronable->Output;

```

**Comment by Maikuolan** [comment]
Cheers. I'll investigate this in the next hour or so.

**Comment by Maikuolan** [comment]
Another user had reported a problem to me via private channels which affected Cronable since introducing CIDRAM's new 2FA feature. I think the issue you're experiencing could be the same issue. If so, it should be resolved as of the latest commit to CIDRAM (problem not replicated since the latest commit).

You may need to update via the front-end at least once, to update to this latest commit, and then from there, Cronable should start working properly again (in theory).

Maybe keep an eye on it for a day or two, in case there's something I've missed, but it should be okay now. Let me know if there are any more problems. :-)

**Comment by harryqt** [comment]
> You may need to update via the front-end at least once

Sounds good. I just updated CIDRAM from the front-end. I will keep an eye on it too.

**Comment by harryqt** [comment]
I can confirm the issue is now **resolved**. "1.8.0-DEV+18246768" was automatically updated. :blush: 
Go ahead and close it. :stuck_out_tongue:

**Comment by Maikuolan** [comment]
Great to hear! Cheers. 😊
